# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Deploy Develop Google Fonts Wrapper

on:
  workflow_dispatch:
  push:
    branches: [ develop ]

jobs:
  deploy:
    name: Build Google Fonts Wrapper
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install rsync
        run: |
          sudo apt-get update
          sudo apt-get install rsync
          sudo apt-get install -y sshpass
      - name: Building Google Fonts Wrapper
        run: |
          yarn install
          yarn build
      - name: Deploying Google Fonts Wrapper
        run: |
          rsync -r -e 'sshpass -p "${{ secrets.DEPLOY_PASSWORD }}" ssh -o StrictHostKeyChecking=no' ./dist/ ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_BASE_URL }}/dev-fonts.pdaus.de
